name: travelmate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.1
  intl: ^0.20.2
  logger: ^2.0.2
  url_launcher: ^6.1.7
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.0
  carousel_slider: ^5.0.0
  flutter_pdfview: ^1.0.0

  # Auth
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^11.3.3
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2
  get: ^4.6.6
  get_storage: ^2.1.1

  # fonts
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.2.1
  webview_flutter: ^4.10.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  flutter_inappwebview: ^6.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^29.1.38
  flutter_svg: ^2.0.17
  mime: ^2.0.0
  html: ^0.15.6
  razorpay_flutter: ^1.4.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
